@startuml Notify alert sequence

Actor Notifier as nf
Participant Server as sv
Queue AWS_SQS as sqs
participant Worker as wk
participant Slack as sl

nf --> sv: Notification request
sv -> sv: Validate request payload

alt Payload ok
    sv --> sqs: Send notify alert event message to queue
    sv --> nf: Request completed
else Invalid payload
    sv --> nf: 400 Bad Request
end

sqs <-- wk: Get message from queue
wk -> wk: Consume message

alt Notification ok
    wk --> sl: Send message to Slack channel
    sqs <-- wk: Delete message from queue
else Error
        alt Retry send notification
            loop
                sqs <-- wk: Release message back to queue
                sqs <-- wk: Get message again after X seconds
                wk -> wk: Retry message
            end
        else Max receive count reached
            sqs <- sqs: Send message to dead letter queue
    end
end

@enduml