version: '3.7'

services:
  server:
    build: 
      context: ../server/
    container_name: ifood-server
    ports:
      - "3000:3000"
    env_file:
      - ../server/conf/default.env
    depends_on:
      localstack:
        condition: service_healthy
    
  slack-notifier-worker:
    build: 
      context: ../workers/slack-notifier
    container_name: ifood-slack-notifier-worker
    env_file:
      - ../workers/slack-notifier/conf/default.env
    depends_on:
      localstack:
        condition: service_healthy
  
  localstack:
    container_name: ifood-localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    healthcheck:
      test: 'curl -s http://localhost:4566/health | grep "\"sqs\": \"running\""'
      interval: 10s
      retries: 6
    environment:
      - SERVICES=sqs
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d/